### PR TITLE
Update windows-provisioner.ps1

### PR DESCRIPTION
**Pull request by MariusKorzeniauskas**
SET system variables msbuild

### CODE REVIEW

**Comment by MariusKorzeniauskas** [comment]
please install .net 4.0 framework in https://github.com/telia-oss/terraform-aws-github-runner/tree/main/images/windows-core-2019

**Comment by mikeharrisontelia** [comment]
Hey @MariusKorzeniauskas  I see the pr here for setting the system variables did you miss some commits. I haven't seen the part for .net 4.0

**Comment by MariusKorzeniauskas** [comment]
I haven't done anything for .net 4.0, I lack expertise. So please install.
Commit here https://github.com/telia-oss/terraform-aws-github-runner/pull/3/commits/e9b4f3713aafb01e10bd5cefcbac596b428dc6b7

**Comment by MariusKorzeniauskas** [comment]
Aš pradedantysis GitHub, tai aš čia galiu pridaryti nesamonių

**Comment by MariusKorzeniauskas** [comment]
we are using msbuild, at this time not using dotnet

**Pull request merged**
